name: Deploy e Merge automático

on:
  pull_request:
    types: [labeled]

jobs:
  deploy-and-merge:
    if: contains(github.event.pull_request.labels.*.name, 'ready-to-merge')
    runs-on: ubuntu-latest

    steps:
      - name: Checkout da branch de origem
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Executar deploy
        run: |
          echo "Executando deploy com base na branch ${{ github.event.pull_request.head.ref }}"
          # seu script de deploy aqui
          # simule erro com: exit 1

      - name: Merge automático se o deploy for bem-sucedido
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --admin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
