on:
  pull_request:
    types: [opened, reopened]
    branches: 'release/**'

jobs:
  validate-branch-origin:
    runs-on: ubuntu-latest
    steps:
      - name: Validate commit message
        if: ${{ !(startsWith(github.head_ref, 'feature/')) }}
        run: echo "Pull request to release branches must come from 'feature' or 'hotfix' branches!" |
          exit 1
